
[client]
showErrorDetails = 'full'

[theme]
base = 'light'

primaryColor = '#1F84B5'
backgroundColor = 'aliceblue'
secondaryBackgroundColor = '#66c6f3fa'

#primaryColor = '#1F84B5'
#secondaryBackgroundColor = '#66c6f3fa'

#1 '#0090D3'
#2 '#1F84B5'
#alice bluer '#AEC6F7'
#'#f0f8ff'
#visual avg of 1 and 2 '#0F8BC8'
#RGB exact avg of 1 and 2 '#108AC4'
#orange to pair with alice bluer '#F2A65A'

baseFontSize = 16
baseFontWeight = 500


#img design: overlay f0f8ff +20/45, saturation +30, round corners 20, resize and save webp


























